version: 2.1
orbs:
  soda-lint: checkmoney/soda-lint@1.0.2
workflows:
  version: 2
  build:
    jobs:
      - soda-lint/invoke:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
