name: Check PR

on: pull_request

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Linting
      run: |
        yarn install
        yarn s lint
  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Check types
      run: |
        yarn install
        yarn types
  circular_dependency:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Check circular dependency
      run: |
        yarn install
        yarn circular
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Automated tests
      run: |
        yarn install
        yarn test
        
